export const ICON_NAMES = {
  info: "info",
  edit: "edit",
  close: "close",
  refresh: "refresh",
  swapHoriz: "swap-horiz",
  swapVert: "swap-vert",
  timer: "timer",
  pause: "pause",
  playArrow: "play-arrow",
  restaurant: "restaurant",
  videocamOff: "videocam-off",
  removeCircleOutline: "remove-circle-outline",
  check: "check",
  arrowDropDown: "arrow-drop-down",
} as const;